#%RAML 1.0 DataType
      properties:
          studentname:
            required: true
            type: string
          studentfathername:
            required: true
            type: string
            description: "Enter Student Father Name"
          studentmothername:
            required: true
            type: string
            description: "Enter Student Mother Name"
          studentmobilenumber:
            required: true
            type: string
            minLength: 10
            maxLength: 10
            description: "Enter Student Mobile Number"
          studentage:
            required: true
            type: number
            description: "Enter Student Age"
          studentaddress:
            required: true
            type: string
            description: "Enter Student Address"
          studentclass:
            required: true
            type: number
            description: "Enter Student classs" 